# Generated by Django 4.1.2 on 2023-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='shop_pictures/', verbose_name='Фотография'),
        ),
    ]
