# Generated by Django 4.2.4 on 2023-08-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_shop_image_shopgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopgallery',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.shop'),
        ),
    ]
